# Generated by Django 3.1.5 on 2021-02-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_slug'),
        ('users', '0002_auto_20210202_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisteredquizzes',
            name='registered_quizzes',
            field=models.ManyToManyField(to='quiz.Quiz'),
        ),
    ]
