# Generated by Django 3.1.5 on 2021-02-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_slug'),
        ('users', '0003_auto_20210203_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregisteredquizzes',
            name='registered_quizzes',
        ),
        migrations.AddField(
            model_name='userregisteredquizzes',
            name='registered_quizzes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
