# Generated by Django 3.1.5 on 2021-02-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210203_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregisteredquizzes',
            old_name='registered_quizzes',
            new_name='registered_quiz',
        ),
    ]
