# Generated by Django 3.1.5 on 2021-02-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_slug'),
        ('users', '0006_auto_20210203_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisteredquizzes',
            name='current_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
