# Generated by Django 3.1.5 on 2021-02-04 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0012_auto_20210203_1440'),
        ('users', '0008_useranswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='useranswers',
            name='answered',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswers',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswers',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswers',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
