# Generated by Django 3.1.5 on 2021-02-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210204_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
