# Generated by Django 3.1.5 on 2021-02-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210205_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
