# Generated by Django 3.1.5 on 2021-02-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210205_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswers',
            old_name='last_updated',
            new_name='working_time',
        ),
    ]
