# Generated by Django 3.1.5 on 2021-02-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210208_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
