# Generated by Django 3.1.5 on 2021-02-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_question_number_of_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
