# Generated by Django 3.1.5 on 2021-02-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answer_title',
        ),
    ]
